const LOADING = 'LOADING';
const LOADED = 'LOADED';
const SIGN_UP_USER_REQUEST = 'SIGN_UP_USER_REQUEST';
const SIGN_UP_USER_REQUEST_SUCCESS = 'SIGN_UP_USER_REQUEST_SUCCESS';
const SIGN_UP_USER_REQUEST_FAILURE = 'SIGN_UP_USER_REQUEST_FAILURE';
const LOGIN_USER = 'LOGIN_USER';
const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
const LOGOUT_USER = 'LOGOUT_USER';
const POST_CAR = 'POST_CAR';
const POST_CAR_SUCCESS = 'POST_CAR_SUCCESS';
const POST_CAR_FAILURE = 'POST_CAR_FAILURE';
const GET_CAR = 'GET_CAR';
const GET_CAR_SUCCESS = 'GET_CAR_SUCCESS';
const GET_CAR_FAILURE = 'GET_CAR_FAILURE';
const GET_CARS = 'GET_CARS';
const GET_CARS_SUCCESS = 'GET_CARS_SUCCESS';
const GET_CARS_FAILURE = 'GET_CARS_FAILURE';
const PART_UPDATE = 'PART_UPDATE';
const PART_UPDATE_SUCCESS = 'PART_UPDATE_SUCCESS';
const PART_UPDATE_FAILURE = 'PART_UPDATE_FAILURE';
const DELETE_CAR = 'DELETE_CAR';
const DELETE_CAR_SUCCESS = 'DELETE_CAR_SUCCESS';
const DELETE_CAR_FAILURE = 'DELETE_CAR_FAILURE';
const ADD_CAR_TO_LIST = 'ADD_CARS_TO_LIST';
const REMOVE_CAR_FROM_LIST = 'REMOVE_CAR_FROM_LIST';
const SET_FILTER_INDEX = 'SET_FILTER_INDEX';
const LOGIN_USER_SESSION = 'LOGIN_USER_SESSION';

export {
  LOADED,
  LOADING,
  SIGN_UP_USER_REQUEST,
  SIGN_UP_USER_REQUEST_SUCCESS,
  SIGN_UP_USER_REQUEST_FAILURE,
  LOGIN_USER,
  LOGIN_USER_SUCCESS,
  LOGIN_USER_FAILURE,
  LOGOUT_USER,
  GET_CAR,
  GET_CAR_SUCCESS,
  GET_CAR_FAILURE,
  GET_CARS,
  GET_CARS_SUCCESS,
  GET_CARS_FAILURE,
  DELETE_CAR,
  DELETE_CAR_SUCCESS,
  DELETE_CAR_FAILURE,
  REMOVE_CAR_FROM_LIST,
  POST_CAR,
  POST_CAR_SUCCESS,
  POST_CAR_FAILURE,
  ADD_CAR_TO_LIST,
  PART_UPDATE,
  PART_UPDATE_SUCCESS,
  PART_UPDATE_FAILURE,
  SET_FILTER_INDEX,
  LOGIN_USER_SESSION,
};
