const SIGN_UP_USER_REQUEST = 'SIGN_UP_USER_REQUEST';
const SIGN_UP_USER_REQUEST_SUCCESS = 'SIGN_UP_USER_REQUEST_SUCCESS';
const SIGN_UP_USER_REQUEST_FAILURE = 'SIGN_UP_USER_REQUEST_FAILURE';
const LOGIN_USER = 'LOGIN_USER';
const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
const LOGOUT_USER = 'LOGOUT_USER';
const POST_CAR = 'POST_CAR';
const POST_CAR_SUCCESS = 'POST_CAR_SUCCESS';
const POST_CAR_FAILURE = 'POST_CAR_FAILURE';
const GET_CAR = 'GET_CAR';
const GET_CAR_SUCCESS = 'GET_CAR_SUCCESS';
const GET_CAR_FAILURE = 'GET_CAR_FAILURE';
const PART_UPDATE = 'PART_UPDATE';
const PART_UPDATE_SUCCESS = 'PART_UPDATE_SUCCESS';
const PART_UPDATE_FAILURE = 'PART_UPDATE_FAILURE';

export {
  SIGN_UP_USER_REQUEST,
  SIGN_UP_USER_REQUEST_SUCCESS,
  SIGN_UP_USER_REQUEST_FAILURE,
  LOGIN_USER,
  LOGIN_USER_SUCCESS,
  LOGIN_USER_FAILURE,
  LOGOUT_USER,
  POST_CAR,
  POST_CAR_SUCCESS,
  POST_CAR_FAILURE,
  GET_CAR,
  GET_CAR_SUCCESS,
  GET_CAR_FAILURE,
  PART_UPDATE,
  PART_UPDATE_SUCCESS,
  PART_UPDATE_FAILURE,
};
