const SIGN_UP_USER_REQUEST = 'SIGN_UP_USER_REQUEST';
const SIGN_UP_USER_REQUEST_SUCCESS = 'SIGN_UP_USER_REQUEST_SUCCESS';
const SIGN_UP_USER_REQUEST_FAILURE = 'SIGN_UP_USER_REQUEST_FAILURE';

export {
  SIGN_UP_USER_REQUEST,
  SIGN_UP_USER_REQUEST_SUCCESS,
  SIGN_UP_USER_REQUEST_FAILURE,
};
